[project]
name = "pyppms"
description = "A Python package to communicate with Stratocore's PUMAPI."
readme = "README.md"
authors = [
  { name = "Niko Ehrenfeuchter", email = "nikolaus.ehrenfeuchter@unibas.ch" },
  { name = "Laurent Guerard", email = "laurent.guerard@unibas.ch" },
]
version = "0.0.0"
requires-python = ">=3.11,<4"

license = "GPLv3"
keywords = ["ppms", "pumapi", "booking-system", "reservation-system"]

dependencies = [
  "requests (>=2.31.0,<3)",
  "loguru (>=0.7.0,<1)",
  "pandas (>2,<3)",
]


[tool.poetry]
name = "pyppms"
version = "0.0.0"
documentation = "https://imcf.one/apidocs/pyppms/pyppms.html"
homepage = "https://pypi.org/project/pyppms/"
repository = "https://github.com/imcf/pyppms"


[tool.poetry.group.dev.dependencies]
pdoc = "14.0.0"
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
pyyaml = "^6.0.3"
ruff = "^0.16.0"
ipython = "<9"

[build-system]
build-backend = "poetry_dynamic_versioning.backend"
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]

[tool.poetry-dynamic-versioning]
enable = true

[tool.pytest.ini_options]
addopts = "-rs -vv --cov=pyppms --cov-report html --maxfail=1"
markers = [
  "online: enables tests requiring connection to a real PUMAPI (as opposed to a local cache)",
]

[tool.ruff.lint]
# exclude = [
#   "tests/foo/*"
# ]

select = [
  "D",
  "D212", # summary lines must be on the first physical line of the docstring
  "D401", # imperative mood for all docstrings
  "D415", # summary line has to end in a punctuation mark
  "D417", # require documentation for _all_ function parameters
]

ignore = [
  "D202", # no blank lines allowed after function docstring
  ## D211 conflicts with ruff's formatting as of 2025-04-14, so don't use it:
  # "D211",  # no blank lines allowed before class docstring
]


[tool.ruff.lint.pydocstyle]
convention = "numpy"
